### ISSUE TITLE
`The dependency target "Arduino_Drv_I2cDriver" of target   "BaremetalReference_Top" does not exist` while running `fprime-util generate`

### ISSUE THREAD

**Issue by capsulecorplab** [fprime-community/fprime-baremetal-reference#9] opened 2023-07-23 23:29 UTC
![Screenshot from 2023-07-23 16-27-44](https://github.com/fprime-community/fprime-baremetal-reference/assets/14095576/98c14e20-850d-4fb8-84ae-63c40938c3a9)

**Comment by ethancheez** [comment] 2023-07-23 23:41
@capsulecorplab 
This is because my PR for the I2C driver hasn't been merged yet. You can either switch to my `fprime-arduino` branch or manually add the I2C driver to your project. 

[https://github.com/ethancheez/fprime-arduino.git](https://github.com/ethancheez/fprime-arduino.git)

My main branch should be updated.

**Comment by capsulecorplab** [comment] 2023-07-24 03:09
Yup, adding your `fprime-arduino` library was able to generate the build cache! Ran into an undefined symbol error while attempting to build though
![Screenshot from 2023-07-23 20-05-07](https://github.com/fprime-community/fprime-baremetal-reference/assets/14095576/9009b1f3-1f0b-41b3-a79c-3d0e4eb5530a)

**Comment by ethancheez** [comment] 2023-07-24 15:09
> Yup, adding your `fprime-arduino` library was able to generate the build cache! Ran into an undefined symbol error while attempting to build though

I was unable to reproduce this error. Could you check your project if `lib/fprime-baremetal/Svc/TlmLinearChan` is included?

**Comment by ethancheez** [comment] 2023-07-24 16:23
> > > Yup, adding your `fprime-arduino` library was able to generate the build cache! Ran into an undefined symbol error while attempting to build though
> > 
> > 
> > I was unable to reproduce this error. Could you check your project if `lib/fprime-baremetal/Svc/TlmLinearChan` is included?
> 
> Yup, `lib/fprime-baremetal/Svc/TlmLinearChan` is there

This was my attempt to reproduce the error:
```
git clone --recurse-submodules  https://github.com/fprime-community/fprime-baremetal-reference.git
cd fprime-baremetal-reference/
fprime-util generate
fprime-util build -j4
```

The build succeeded, generating binaries for all deployments: `BaremetalReference`, `RadioPassthrough`, and `BaseDeployment`. My only theory on why the `undefined symbol` error occurs is if the `fprime-baremetal/Svc/TlmLinearChan/TlmLinearChan.fpp` file is not included.

If you navigate directly into the `lib/fprime-baremetal/Svc/TlmLinearChan` directory and run `fprime-util build`, does it build?

**Comment by capsulecorplab** [comment] 2023-07-24 21:50
> The `settings.ini` file should include:
> 
> ```
> library_locations:  ./lib/arduino/fprime-arduino:./lib/fprime-baremetal
> ```

Ah, that could be the issue. I commented that line out and replaced it with just a path to your fork of `fprime-arduino`
![Screenshot from 2023-07-24 14-44-51](https://github.com/fprime-community/fprime-baremetal-reference/assets/14095576/a2610879-5d0d-4f8b-be16-de5bb0b7219c)

Let me fix that...

**Comment by capsulecorplab** [comment] 2023-07-24 22:01
I reverted any changes to settings.ini and set the head commit in `lib/arduino/fprime-arduino` to your fork and that fixed the build!
![Screenshot from 2023-07-24 14-53-06](https://github.com/fprime-community/fprime-baremetal-reference/assets/14095576/20bb3932-f6ba-4ef4-b544-f2973ed4c91b)
![Screenshot from 2023-07-24 14-58-11](https://github.com/fprime-community/fprime-baremetal-reference/assets/14095576/99f8e7b2-452c-4386-af17-f297159a4888)

Now I just need to wait for my Teensy 4.1 to arrive in the mail to actually flash/test it :upside_down_face:

**Comment by ethancheez** [comment] 2023-07-24 22:18
> Now I just need to wait for my Teensy 4.1 to arrive in the mail to actually flash/test it :upside_down_face: 

The baremetal reference uses the RFM69 radio to communicate. You would also need two [RFM69 breakout boards](https://www.adafruit.com/product/3070?gclid=EAIaIQobChMI7J6N9qyogAMVcczCBB2KSAsWEAQYASABEgJnjPD_BwE) and two Teensy 4.1 boards. 

Or you can get two [Feather M0s](https://www.adafruit.com/product/3176)

**Comment by capsulecorplab** [comment] 2023-07-24 22:34
> The baremetal reference uses the RFM69 radio to communicate. You would also need two [RFM69 breakout boards](https://www.adafruit.com/product/3070?gclid=EAIaIQobChMI7J6N9qyogAMVcczCBB2KSAsWEAQYASABEgJnjPD_BwE) and two Teensy 4.1 boards.
> 
> Or you can get two [Feather M0s](https://www.adafruit.com/product/3176)

Cool! Any advantage to getting two [Feather M0s](https://www.adafruit.com/product/3176) over two [RFM69 breakout boards](https://www.adafruit.com/product/3070?gclid=EAIaIQobChMI7J6N9qyogAMVcczCBB2KSAsWEAQYASABEgJnjPD_BwE)? What would the 2nd Teensy be for?

**Comment by ethancheez** [comment] 2023-07-24 22:39
> > The baremetal reference uses the RFM69 radio to communicate. You would also need two [RFM69 breakout boards](https://www.adafruit.com/product/3070?gclid=EAIaIQobChMI7J6N9qyogAMVcczCBB2KSAsWEAQYASABEgJnjPD_BwE) and two Teensy 4.1 boards.
> 
> > 
> 
> > Or you can get two [Feather M0s](https://www.adafruit.com/product/3176)
> 
> 
> 
> Cool! Any advantage to getting two [Feather M0s](https://www.adafruit.com/product/3176) over two [RFM69 breakout boards](https://www.adafruit.com/product/3070?gclid=EAIaIQobChMI7J6N9qyogAMVcczCBB2KSAsWEAQYASABEgJnjPD_BwE)? What would the 2nd Teensy be for?

There are two separate deployments that communicate to each other via the radio: `BaremetalReference` and `RadioPassthrough`. 

One Teensy would have the BaremetalReference deployment, and the other Teensy would have the RadioPassthrough deployment. Your GDS would connect to the RadioPassthrough deployment to wirelessly command the BaremetalReference deployment.

**Comment by capsulecorplab** [comment] 2023-07-24 23:59
Ordered a couple of the radio breakout boards + an extra teensy - might as well test with all the platforms :slightly_smiling_face:

**Comment by capsulecorplab** [comment] 2023-07-25 00:02
I guess I'll go ahead and close this issue and open any new issues that may arise when attempting to connect and test with hardware. Thanks for all the help @ethancheez !

**Comment by capsulecorplab** [comment] 2023-07-25 00:09
I also just noticed there's a [433MHz](https://www.adafruit.com/product/3071) option that's license-free (which means I don't have to renew my ham license). Would this work as well?

**Comment by ethancheez** [comment] 2023-07-25 00:14
> I also just noticed there's a [433MHz](https://www.adafruit.com/product/3071) option that's license-free (which means I don't have to renew my ham license). Would this work as well?

Yes, I believe both the 433 MHz and 915 MHz bands do not require a HAM Radio License. As long as both of your radios operate at the same frequency, you should be fine!

**Comment by capsulecorplab** [comment] 2023-08-18 19:15
Re-opening this issue, as the `fprime-arduino` submodule doesn't contain @ethancheez's i2c drivers yet

**Closed** 2023-08-18 19:25 UTC
